name: Build Windows Flash Tool EXE

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller esptool pyserial

      - name: Debug list files
        shell: cmd
        run: |
          echo ===== ROOT =====
          dir
          echo ===== FILES =====
          dir firmware.bin
          dir version.json

      - name: Build EXE (onefile)
        shell: cmd
        run: |
          pyinstaller --noconfirm --onefile --console ^
            --name AutoGenX_FlashTool ^
            --add-data "firmware.bin;." ^
            --add-data "version.json;." ^
            autogen_flash.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoGenX_FlashTool_Windows
          path: dist/AutoGenX_FlashTool.exe
